pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo building'
                sh 'cp env.sample .env'

                sh 'python3 -m venv venv'

                sh '. venv/bin/activate && pip install --upgrade pip'
                sh '. venv/bin/activate && pip install -r requirements.txt'

            }
        }

        stage('Test') {
            steps {
                sh 'echo testing'
                sh '. venv/bin/activate && python manage.py test'
            }
        }

        stage('Backup deployment') {
            steps {
                sshagent(['ec2-jenkins-key']) {
                    sh 'ssh ubuntu@<production_server_1_ip> -o StrictHostKeyChecking=no "bash /var/www/project5/scripts/deploy.sh"'
                }
            }
        }

        stage('Deploy to production') {
            input {
                message "Shall we deploy to production?"
                ok "Yes please"
            }
            steps {
                sh 'ssh root@<production_server_2_ip> -o StrictHostKeyChecking=no "bash /var/www/project5/scripts/deploy.sh"'
            }
        }
    }

    post {
        failure {  
             mail bcc: '', body: "<b>Failed Jenkins Build</b><br>Project: ${env.JOB_NAME} \
             <br>Build Number: ${env.BUILD_NUMBER} <br> URL of the build: ${env.BUILD_URL}", cc: '', \
             charset: 'UTF-8', from: '<email>', mimeType: 'text/html', replyTo: '<email>', \
             subject: "ERROR CI: Project name -> ${env.JOB_NAME}", \
             to: "<email>";  \
         }
    }

}
